# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GRAL.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from sensor import Ui_MainWindow


class Ui_General(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()


    def setupUi(self, General):
        General.setObjectName("General")
        General.resize(790, 600)
        self.centralwidget = QtWidgets.QWidget(General)
        self.centralwidget.setObjectName("centralwidget")
        self.GRAL = QtWidgets.QFrame(self.centralwidget,)
        self.GRAL.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.GRAL.setStyleSheet("background-color:rgb(163, 191, 120);\n"
"border-radius: 5px;\n"
"\n"
"")
        self.GRAL.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GRAL.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GRAL.setObjectName("GRAL")
        self.user = QtWidgets.QPushButton(self.GRAL)
        self.user.setGeometry(QtCore.QRect(60, 50, 41, 41))
        self.user.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Pictures/usuario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user.setIcon(icon)
        self.user.setIconSize(QtCore.QSize(70, 50))
        self.user.setObjectName("user")
        self.home = QtWidgets.QPushButton(self.GRAL)
        self.home.setGeometry(QtCore.QRect(660, 50, 31, 31))
        self.home.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Pictures/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon1)
        self.home.setObjectName("home")
        self.comboBox = QtWidgets.QComboBox(self.GRAL)
        self.comboBox.setGeometry(QtCore.QRect(140, 50, 491, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(162, 180, 168);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.GRAL)
        self.label.setGeometry(QtCore.QRect(290, 200, 221, 341))
        self.label.setStyleSheet(""),
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../awita/awitaa.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.GRAL , clicked= lambda:self.openWindow())
        self.pushButton.setGeometry(QtCore.QRect(300, 350, 201, 28))
        self.pushButton.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"background-color: rgb(85, 170, 0);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.GRAL)
        self.textEdit.setGeometry(QtCore.QRect(90, 120, 621, 61))
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        General.setCentralWidget(self.centralwidget)

        self.retranslateUi(General)
        QtCore.QMetaObject.connectSlotsByName(General)

    def retranslateUi(self, General):
        _translate = QtCore.QCoreApplication.translate
        General.setWindowTitle(_translate("General", "MainWindow"))
        self.comboBox.setItemText(0, _translate("General", "Administrador"))
        self.comboBox.setItemText(1, _translate("General", "General"))
        self.pushButton.setText(_translate("General", "Continuar"))
        self.textEdit.setHtml(_translate("General", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Century Gothic\'; font-size:12pt; color:#000000;\">Se iniciará sesión en modo general</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    General = QtWidgets.QMainWindow()
    ui = Ui_General()
    ui.setupUi(General)
    General.show()
    sys.exit(app.exec_())
