# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sistema.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from sensorfinal import Ui_Sensorfinal


class Ui_Admin_modo(object):

    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Sensorfinal()
        self.ui.setupUi(self.window)
        self.window.show()


    def setupUi(self, Admin_modo):
        Admin_modo.setObjectName("Admin_modo")
        Admin_modo.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Admin_modo)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fondo = QtWidgets.QFrame(self.centralwidget)
        self.fondo.setStyleSheet("background-color:rgb(163, 191, 120);\n"
"border-radius: 5px;\n"
"\n"
"")
        self.fondo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fondo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fondo.setObjectName("fondo")
        self.user = QtWidgets.QPushButton(self.fondo)
        self.user.setGeometry(QtCore.QRect(60, 50, 41, 41))
        self.user.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Pictures/usuario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user.setIcon(icon)
        self.user.setIconSize(QtCore.QSize(70, 50))
        self.user.setObjectName("user")
        self.home = QtWidgets.QPushButton(self.fondo, clicked= lambda: self.openWindow())
        self.home.setGeometry(QtCore.QRect(660, 50, 31, 31))
        self.home.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Pictures/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon1)
        self.home.setObjectName("home")
        self.ADM = QtWidgets.QFrame(self.fondo)
        self.ADM.setGeometry(QtCore.QRect(30, 330, 231, 221))
        self.ADM.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 18px;")
        self.ADM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ADM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ADM.setObjectName("ADM")
        self.textBrowser = QtWidgets.QTextBrowser(self.ADM)
        self.textBrowser.setGeometry(QtCore.QRect(30, 160, 81, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.ADM)
        self.textBrowser_2.setGeometry(QtCore.QRect(30, 100, 81, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.ADM)
        self.textBrowser_5.setGeometry(QtCore.QRect(110, 10, 121, 81))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textEdit_2 = QtWidgets.QTextEdit(self.ADM)
        self.textEdit_2.setGeometry(QtCore.QRect(130, 100, 81, 41))
        self.textEdit_2.setStyleSheet("\n"
"background-color: rgb(138, 140, 90);\n"
"border-radius: 18px;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.ADM)
        self.textEdit_3.setGeometry(QtCore.QRect(130, 160, 81, 41))
        self.textEdit_3.setStyleSheet("background-color: rgb(138, 140, 90);\n"
"border-radius: 18px;\n"
"")
        self.textEdit_3.setObjectName("textEdit_3")
        self.frame_2 = QtWidgets.QFrame(self.fondo)
        self.frame_2.setGeometry(QtCore.QRect(540, 330, 221, 221))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 18px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_3.setGeometry(QtCore.QRect(30, 110, 101, 61))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_4.setGeometry(QtCore.QRect(30, 170, 111, 41))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_6.setGeometry(QtCore.QRect(110, 20, 111, 81))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_4.setGeometry(QtCore.QRect(120, 100, 81, 41))
        self.textEdit_4.setStyleSheet("background-color: rgb(138, 140, 90);\n"
"border-radius: 18px;")
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_5.setGeometry(QtCore.QRect(120, 160, 81, 41))
        self.textEdit_5.setStyleSheet("background-color: rgb(138, 140, 90);\n"
"border-radius: 18px;")
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit = QtWidgets.QTextEdit(self.fondo)
        self.textEdit.setGeometry(QtCore.QRect(80, 110, 621, 61))
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.fondo)
        self.label.setGeometry(QtCore.QRect(290, 200, 221, 361))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../awita/awitaa.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.fondo,clicked= lambda: self.openWindow())
        self.pushButton.setGeometry(QtCore.QRect(300, 560, 201, 28))
        self.pushButton.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"background-color: rgb(85, 170, 0);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.fondo)
        self.textBrowser_7.setGeometry(QtCore.QRect(90, 260, 121, 41))
        self.textBrowser_7.setStyleSheet("\n"
"background-color: rgb(85, 170, 0);\n"
"border-radius: 18px;")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.fondo)
        self.textBrowser_11.setGeometry(QtCore.QRect(580, 260, 121, 41))
        self.textBrowser_11.setStyleSheet("\n"
"background-color: rgb(85, 170, 0);\n"
"border-radius: 18px;")
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.editar_planta1 = QtWidgets.QPushButton(self.fondo)
        self.editar_planta1.setGeometry(QtCore.QRect(220, 260, 31, 31))
        self.editar_planta1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Pictures/ediatrrr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editar_planta1.setIcon(icon2)
        self.editar_planta1.setObjectName("editar_planta1")
        self.editar_planta2 = QtWidgets.QPushButton(self.fondo)
        self.editar_planta2.setGeometry(QtCore.QRect(710, 260, 31, 31))
        self.editar_planta2.setText("")
        self.editar_planta2.setIcon(icon2)
        self.editar_planta2.setObjectName("editar_planta2")
        self.comboBox = QtWidgets.QComboBox(self.fondo)
        self.comboBox.setGeometry(QtCore.QRect(160, 50, 491, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(162, 180, 168);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.fondo)
        Admin_modo.setCentralWidget(self.centralwidget)

        self.retranslateUi(Admin_modo)
        QtCore.QMetaObject.connectSlotsByName(Admin_modo)

    def retranslateUi(self, Admin_modo):
        _translate = QtCore.QCoreApplication.translate
        Admin_modo.setWindowTitle(_translate("Admin_modo", "MainWindow"))
        self.textBrowser.setHtml(_translate("Admin_modo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Mínimo</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Admin_modo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Máximo</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("Admin_modo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Valor de</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">humedad </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">%</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Admin_modo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Máximo</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Admin_modo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Mínimo</span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("Admin_modo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Valor de</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">humedad %</span></p></body></html>"))
        self.textEdit.setHtml(_translate("Admin_modo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Century Gothic\'; font-size:12pt; color:#000000;\">Ingresa los valores máximo y mínimo de humedad de cada planta</span><span style=\" font-size:12pt;\"> </span></p></body></html>"))
        self.pushButton.setText(_translate("Admin_modo", "Guardar cambios"))
        self.textBrowser_7.setHtml(_translate("Admin_modo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Planta 1</span></p></body></html>"))
        self.textBrowser_11.setHtml(_translate("Admin_modo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Planta 2</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Admin_modo", "Administrador"))
        self.comboBox.setItemText(1, _translate("Admin_modo", "General"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Admin_modo = QtWidgets.QMainWindow()
    ui = Ui_Admin_modo()
    ui.setupUi(Admin_modo)
    Admin_modo.show()
    sys.exit(app.exec_())
